### ISSUE TITLE
ODE simulations fail to handle piecewise functions when starting from an equilibrium state

### ISSUE THREAD

**Issue by yjzhang** [sys-bio/tellurium#579] opened 2023-12-15 23:15 UTC
Python version: 3.10.6
Tellurium version: 2.2.8
OS: Linux Mint 21
Running in a jupyter notebook

Consider the following code:

```python
basic_model_desc = """
species X1;

X1' = -k*X1 + u;

X1 = 0;

k = 0.1;

day1 = 1;
day2 = 2;
in_interval := (time >= day1 && time <= day1 + 0.5) || (time >= day2 && time <= day2 + 0.5);
u := piecewise(3000, in_interval, 0);
"""

basic_model = te.loada(basic_model_desc)
result = basic_model.simulate(0, 30, 1000, selections=['time', 'X1', 'u'])
plt.plot(result['time'], result['X1'])
```

I would expect that `X1` would jump up at times t=1 and t=2, but instead, X1 stays at 0 all the time.
![X1 = 0 remains flat](https://github.com/sys-bio/tellurium/assets/1285881/727b3f12-9abf-4f14-b912-e5b89121f7bb)

This does not happen if the initial condition is `X1 = 1`, or when `day1 = 0` - I see the expected behavior in those cases. (figure is for X1 = 1)

![X1 = 1 has jumps at t=1 and t=2](https://github.com/sys-bio/tellurium/assets/1285881/2da4a768-8cc7-435a-8e9a-a67854643657)

It seems like when `X1 < 1e-8`, the piecewise effect fails to work.

Maybe it's something to do with the integrator? Is there an integrator setting that would make this work?

**Comment by luciansmith** [comment] 2023-12-15 23:41
I can reproduce your results, and am equally confused!  I think you might be right that something in the integrator isn't working properly; if you plot u or in_interval, those values are indeed changing in time.

I tried changing the tolerances, but that didn't seem to help.  I will investigate further, but in the meantime, I can at least say that if you use events instead of piecewise, that works fine, even when X1 starts at 0:

```python
import tellurium as te
import roadrunner
import matplotlib.pyplot as plt

basic_model_desc = """
species X1;

X1' = -k*X1 + u;

X1 = 0;

k = 0.1;

day1 = 1;
day2 = 2;
u = 0
at time > day1: u = 3000
at time > day1+0.5: u = 0
at time > day2: u = 3000
at time > day2 + 0.5: u = 0
#in_interval := (time >= day1 && time <= day1 + 0.5) || (time >= day2 && time <= day2 + 0.5);
#u := piecewise(3000, in_interval, 0);
"""

basic_model = te.loada(basic_model_desc)
# basic_model.integrator.relative_tolerance = 1e-9
result = basic_model.simulate(0, 30, 10000, selections=['time', 'X1', 'u'])
basic_model.plot()
plt.plot(result['time'], result['X1'])
```

**Comment by yjzhang** [comment] 2023-12-16 01:02
Thanks, I was able to confirm that using events rather than piecewise works in this instance. I have no idea why they would be different, though...

**Comment by luciansmith** [comment] 2023-12-16 21:27
A further note:  if you convert the rate rule to a reaction, you can then view dX1/dt as X1'.  Which changes correctly!  But X1 still doesn't actually change, and stays put at 0.  It's very odd.

```python
import tellurium as te
import matplotlib.pyplot as plt

basic_model_desc = """
species X1;

 -> X1 ; -k*X1 + u;

X1 = 0.000;

k = 0.1;

day1 = 1;
day2 = 2;
in_interval := (time >= day1 && time <= day1 + 0.5) || (time >= day2 && time <= day2 + 0.5);
u := piecewise(3000, in_interval, 0);
"""

basic_model = te.loada(basic_model_desc)
# basic_model.integrator.relative_tolerance = 1e-9
result = basic_model.simulate(0, 30, 10000, selections=['time', 'X1', 'u', "X1'"])
basic_model.plot()
```

**Comment by luciansmith** [comment] 2024-01-19 19:46
A further explanation:  it turns out that the CVODE integrator, if it's at 0 and continuing to be zero, starts checking ahead to see if this ever changes:  it checks at time 0.01, 0.1, 1, 10, etc. as it reaches those new times.  So here, it just happens to completely miss the piecewise window.  If you change the window around, you can find areas where it works again, because the pieceiwse

Events are handled in a completely different way--when an event triggers, the whole model gets set to that discontinuity, and simulation restarts again.  Another point in the event's favor is that since there's one even that bumps 'u' up, and a different event that bumps 'u' down again, the triggers change from false to true and then *stay* true, so it's easy to notice that they've fired.

One option might be to create a piecewise-to-event translator for SBML files that we run in the background to ensure that they're noticed; it might also theoretically be possible to include event-like root-finding algorithms for the model when piecewise changes happen.  Further updates to come!

**Comment by matthiaskoenig** [comment] 2024-01-21 07:41
Yes, please convert this to events. 
I saw this also a lot with piecewise functions which are only triggered for a very short amount of time. Normally it helps to make the tolerances more strict or set the minimal step size for the integrator (i.e. if you know that your piecewice switches within 0.5 time steps you can set the minimal time step for the integrator < 0.5 (of course this slows integration down).
I.e. if fast piecewise switches will work depends a lot on the integrator simulation settings.

**Comment by luciansmith** [comment] 2024-02-02 22:02
This is now fixed with https://github.com/sys-bio/roadrunner/pull/1180 and will be part of the roadrunner 2.6.0 release.

I ended up not literally converting these to events, but instead converting the piecewise conditions to 'triggers'.  Then, just like we do rootfinding for event triggers, we now also do rootfinding for these 'piecewise triggers'.  If a piecewise function is found of the form:

piecewise(val1, cond1, val2, cond2, val_otherwise)

we now perform rootfinding for:

if(cond1)
if(cond2 && !cond1)
if(!cond1 && !cond2)

What led me to realize that this would work is that I found I could add a generic event with those triggers that didn't even change any values, but because the simulation was paused at those points, the interpretation of the piecewise function was correct.

**Closed as completed** 2024-10-02 02:15 UTC
