### ISSUE TITLE
setSeed not working

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#124] opened 2016-04-24 16:47 UTC
Just tried setSeed with latest tellurium master fdfc48f1f713eab1a4288255aeffdda3251d7de0 and roadrunner develop c27d9adc9af477efc96f159b3ae91854a53363e4 and it doesn't work. Here's the working example (from sys-bio/roadrunner#318):

```
import tellurium as te
import random
from roadrunner import Logger
Logger.setLevel(Logger.LOG_DEBUG)

r = te.loada("""
J0: TetR->; kTbye * TetR

TetR = 1; // Note one molecule
kTbye = 0.1;
""")

myseed = random.randint(1, 100)
r.setIntegrator('gillespie')
r.getIntegrator().setValue('variable_step_size', True)
r.setSeed(myseed)
m = r.simulate(0,100,steps=10)
r.plot()

print(m)
```

**Comment by matthiaskoenig** [comment] 2016-04-26 07:36
Cannot reproduce (see below). Repeated simulation with same seed gives the same simulation result.
I will try again with latest roadrunner commit. Rerunning the code (with different random number) gives different results, but all simulation with same seed give same results.
```
%matplotlib inline
import tellurium as te
import random
from roadrunner import Logger
Logger.setLevel(Logger.LOG_DEBUG)

r = te.loada("""
J0: TetR->; kTbye * TetR

TetR = 1; // Note one molecule
kTbye = 0.1;
""")

myseed = random.randint(1, 100)
r.setIntegrator('gillespie')
r.getIntegrator().setValue('variable_step_size', True)
for k in range(10):
    r.reset()
    r.setSeed(myseed)
    m = r.simulate(0,100,steps=10)
    r.plot(show=False, loc=None)
```
![index](https://cloud.githubusercontent.com/assets/900538/14810209/f6a18710-0b91-11e6-8fc3-96d46cf27167.png)
Second simulation: Now different rand, but all simulations in loop use same seed
![index2](https://cloud.githubusercontent.com/assets/900538/14810255/459dc34c-0b92-11e6-9744-fbb3b2f42eeb.png)

**Comment by matthiaskoenig** [comment] 2016-04-26 07:48
@0u812 Could you specify what does not work?
I just tried with latest roadrunner develop and tellurium master and everything looks correct to me

**Comment by matthiaskoenig** [comment] 2016-05-19 09:03
I will close this. Everything is working as far as I can tell.

**Closed by matthiaskoenig** 2016-05-19 09:03 UTC
