### ISSUE TITLE
Creating submodular reactions on python using Antimony

### ISSUE THREAD

**Issue by MikalD** [sys-bio/tellurium#556] opened 2022-04-07 12:03 UTC
Hi, I have been trying to create submodular reaction on Python with Antimony using the syntax showed on this page https://tellurium.readthedocs.io/en/latest/antimony.html but I always get the following error message : Exception: Antimony: Error in model string, line 3:  syntax error, unexpected '('.

**Comment by matthiaskoenig** [comment] 2022-04-07 12:29
Please provide the concrete example, i.e. post the code you use to create the model. Without seeing the model string this cannot be debugged.

**Comment by MikalD** [comment] 2022-04-07 13:06
Here is the code I am using. Thank you for your time.

```python
y1 = '''
model side_reaction1
    -> y1; bp*y1;
    bp = 0.9;
    y1 -> ; ampi*y3*y1;
    ampi=0.5;
    y1 -> y2; bsp*y1*pow(y5,ns)/(pow(y5,ns)+pow(Ts,ns));
    bsp=10;
    ns=4;
    Ts=1;
    y2 -> y1; awpa*y4*y2;
    awpa = 0.14;
    y1 -> ; api*y1;
    api=2;
    y2 -> ; ampa*y3*y2;
    ampa=1.4;
    -> y3 ; bmi*y3;
    bmi=0.2;
    y3 -> ; asm2*y3*y5;
    asm2 = 0.1 ;
    y3 -> ; am*y3;
    am=1;
    y4 -> ; aw*y4 ;
    aw=0.7 ;
    -> y5 ; bs2*(damage-c);
    bs2=5.5 ;
    c=0;
    damage=1;
    y5 -> ; as*y5;
    as=7.5;
    y1=1;
    y2=1;
    y4=1;
    y3=1;
    y5=1;
    
end
'''

# y2 with delay 1
y2_1 = '''
model side_reaction2
    -> y3; bm*y2
end
'''

#y2 with delay delay 2
y2_2='''
model side_reaction3
    -> y4;bw*y2
end
'''


model3= '''
model total
    A: side_reaction1();
    B: side_reaction2();
    C: side_reaction3();
end
'''


r=te.loada(model3)

r.simulate(0, 50, 100)
r.plot()
```

*edit MK: code formating

**Comment by matthiaskoenig** [comment] 2022-04-07 16:06
@MikalD I could reproduce the issue. I think it has something to do with the ordering of your elements in the model definition. I would always make a clear separation into `parameters`, `species` and ` reactions` sections. And clearly define what are species. Just the reordering solved the issue for me.

I.e. use the following instead of your order
```python
import tellurium as te

y1 = '''
model side_reaction1
    
    bp = 0.9;
    ampi = 0.5;
    bsp = 10;
    ns = 4;
    Ts = 1;
    awpa = 0.14;
    api = 2;
    ampa = 1.4;
    bmi = 0.2;
    asm2 = 0.1;
    am = 1;
    aw = 0.7;
    bs2 = 5.5;
    c = 0;
    damage = 1;
    as = 7.5;
    
    -> y1; bp*y1;
    y1 -> ; ampi*y3*y1;
    y1 -> y2; bsp*y1*pow(y5,ns)/(pow(y5,ns)+pow(Ts,ns));
    y2 -> y1; awpa*y4*y2;
    y1 -> ; api*y1;
    y2 -> ; ampa*y3*y2;
    -> y3 ; bmi*y3;
    y3 -> ; asm2*y3*y5;
    y3 -> ; am*y3;
    y4 -> ; aw*y4 ;
    -> y5 ; bs2*(damage-c);
    y5 -> ; as*y5;

    species y1 = 1;
    species y2 = 1;
    species y4 = 1;
    species y3 = 1;
    species y5 = 1;
end
'''
r = te.loada(y1)
```

You can use markdown and backslashes for code blocks here on github. Your code will be much easier to read. I edited this on your comment above.
Best M

**Comment by luciansmith** [comment] 2022-04-07 16:42
The problem is not the ordering of elements, the problem is that the model3 string has no idea what the three side reactions are, because they're stored in completely separate strings.  Antimony needs to know about all of them at once for it to work.

If you join them all together, it is parsed correctly, and then you get new error messages about missing initial values for parameters.  Adding those in as '1', you get:

```python
import tellurium as te

y1 = '''
model side_reaction1
    -> y1; bp*y1;
    bp = 0.9;
    y1 -> ; ampi*y3*y1;
    ampi=0.5;
    y1 -> y2; bsp*y1*pow(y5,ns)/(pow(y5,ns)+pow(Ts,ns));
    bsp=10;
    ns=4;
    Ts=1;
    y2 -> y1; awpa*y4*y2;
    awpa = 0.14;
    y1 -> ; api*y1;
    api=2;
    y2 -> ; ampa*y3*y2;
    ampa=1.4;
    -> y3 ; bmi*y3;
    bmi=0.2;
    y3 -> ; asm2*y3*y5;
    asm2 = 0.1 ;
    y3 -> ; am*y3;
    am=1;
    y4 -> ; aw*y4 ;
    aw=0.7 ;
    -> y5 ; bs2*(damage-c);
    bs2=5.5 ;
    c=0;
    damage=1;
    y5 -> ; as*y5;
    as=7.5;
    y1=1;
    y2=1;
    y4=1;
    y3=1;
    y5=1;
    
end

model side_reaction2
    -> y3; bm*y2
    bm = 1
    y2 = 1
end

model side_reaction3
    -> y4;bw*y2
    bw= 1
    y2 = 1
end

model total
    A: side_reaction1();
    B: side_reaction2();
    C: side_reaction3();
end
'''


r=te.loada(y1)

r.simulate(0, 50, 100)
r.plot()
```

This still needs work, since you need to connect the elements of your three submodels.  But at least it's parsed correctly.

**Comment by matthiaskoenig** [comment] 2022-04-07 17:15
The problem reported already exists in the model y1. Reordering solved the
issue with the model y1.

**Comment by luciansmith** [comment] 2022-04-07 18:18
Model y1 worked as written for me.  What version of antimony/rr are you using?  I have

te.getVersionInfo()
Out[9]: 
[('tellurium', '2.2.2.1'),
 ('roadrunner', '2.2.1'),
 ('rrplugins', '2.2.0'),
 ('antimony', '2.12.0.3'),
 ('libsbml', '5.19.2'),
 ('libsedml', '2.0.26'),
 ('phrasedml', '1.1.1')]

**Comment by MikalD** [comment] 2022-04-08 08:47
Thank for your answers. @luciansmith, your solution works for me (however when I modify my code instead of copy+paste what you wrote, I get : syntax error, unexpected '('). Here are the info version info of antimony on my computer :
[('tellurium', '2.2.2.1'),
 ('roadrunner', '2.0.5'),
 ('rrplugins', '2.0.4'),
 ('antimony', '2.12.0'),
 ('libsbml', '5.19.3'),
 ('libsedml', '2.0.29'),
 ('phrasedml', '1.1.1')]

**Comment by luciansmith** [comment] 2022-04-08 13:48
I would recommend upgrading roadrunner, but I'm glad it works!  Closing this issue, but feel free to re-open or create a new one i you have more questions.

**Closed as completed by luciansmith** 2022-04-08 13:48 UTC
