### ISSUE TITLE
Error concerning "unexpected name of existing function" in reaction definition of antimony model

### ISSUE THREAD

**Issue by Koenvz98** [sys-bio/tellurium#557] opened 2022-04-12 11:05 UTC
When trying to load a model written using antimony, I get the error message: 
Exception: Antimony: Error in model string, line 49:  syntax error, unexpected name of an existing function.

For context: I define a number of function Ids, which are then used in reactions that are simulated over time. The error occurs for one of the reactions, but this reaction is formatted in the exact same way as all the other reactions. None of these other reactions give an error.

I am using the python package with python version 3.9.7 and tellurium version 2.2.2.1 on windows 10.

### General set-up:
model = te.loada("""
  listOfFunctionDefinitions

model model_name()

  listOfUnitDefinitions

  listOfCompartments
  
  listOfSpecies

  listOfParameters

  listOfReactions
end
""")
followed by simulation, but the error occurs in the loading of the model.

### Example of function Ids:

  function Function_for_CYTBO(Vmax_CYTBO, Hin, Hout, Keq_CYTBO, O2, QH2, Q)
    Vmax_CYTBO /  (1 + pow(ln(Hout / Hin) / ln(10), 2))  * (pow(QH2, 2) * O2 - pow(Q, 2) / Keq_CYTBO)
  end
  function Function_for_SQR(FADH2, Q, FAD, QH2, Keq_SQR, Vmax_SQR)
    Vmax_SQR * (FADH2 * Q - FAD * QH2 / Keq_SQR)
  end
  function Function_for_NDH2(Vmax_NDH2, NADH, Q, NAD, QH2, KeqNDH)
    Vmax_NDH2 * (NADH * Q - NAD * QH2 / KeqNDH)
  end

### Example of reactions: 

  CYTBO : 2 QH2 + 8 $Hin + $O2 => 2 Q + 8 Hout + 2 $H2O; Function_for_CYTBO(Vmax_CYTBO, Hin, Hout, Keq_CYTBO, O2, QH2, Q)
  SQR : FADH2 + Q => FAD + QH2; cell * Function_for_SQR(FADH2, Q, FAD, QH2, Keq_SQR, Vmax_SQR)
  NDHII : NADH + Q => NAD + QH2; cell * Function_for_NDH2(Vmax_NDH2, NADH, Q, NAD, QH2, KeqNDH)

The error occurs for the SQR reaction. If I comment out this line, the model simulates without issue, however, at this point the model is obviously no longer correct. To reproduce the bug, if desired, simply loading the example function ids and reactions I gave above is enough.
I cannot see any difference between this reaction and any of the others in the model, and as such do not know what causes this issue. I would like to inquire whether there is a known solution available for this error. Thanks in advance.

**Comment by luciansmith** [comment] 2022-04-12 16:58
This is an obscure problem!  The issue is that 'SQR' is the name of the 'square' function, so Antimony doesn't like you using it for the name of a reaction.  If you change it to 'SQR1' or something, your model will work again.

That's what it meant by 'unexpected name of an existing function':  'SQR' is the name of an existing function, and it didn't expect to see it as the name of a reaction.

Because of issues like this, the next version of Antimony (2.13) is going to have case-sensitive reserved words, so that only 'sqr' is reserved, and 'SQR' won't be, which will at least somewhat alleviate the problem.

**Comment by luciansmith** [comment] 2023-01-25 20:39
As a note:  the now-released version of Antimony that won't think that 'SQR' is the 'square' function.  It still reserves the string 'sqr' but only the lower-cased version.  Closing this, but feel free to re-open if you have any other issues!

**Closed as completed by luciansmith** 2023-01-25 20:39 UTC
